### ISSUE TITLE
production ready formula

### ISSUE THREAD

**Issue by jstrunk** [saltstack-formulas/sumo-logic-formula#1]
How do y'all feel about replacing this empty formula with the one at https://github.com/metamx/sumo-logic-formula ?

Regards,
Jeff

**Comment by gtmanfred** [comment]
@nmadhok would you be ok if we replace this formula with the one listed here?

**Comment by nmadhok** [comment]
@gtmanfred I'm fine with that!

**Comment by gtmanfred** [comment]
I am going to delete this formula and pull the other formula over.

Thanks!
Daniel
